# Generated by Django 4.2.6 on 2023-12-22 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_team_of_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='team_of_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.team'),
        ),
    ]
