# Generated by Django 4.2.6 on 2023-12-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_team_task_user_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='user',
            name='invites',
            field=models.ManyToManyField(blank=True, related_name='invites', to='tasks.team'),
        ),
    ]
