# Generated by Django 4.2.6 on 2023-12-04 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_team_task_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='team',
        ),
    ]
