# Generated by Django 4.2.6 on 2023-11-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_status'),
        ('tasks', '0004_team'),
    ]

    operations = [
    ]
