# Generated by Django 4.2.6 on 2023-12-04 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_team_task_team'),
        ('tasks', '0005_remove_task_team'),
    ]

    operations = [
    ]
