# Generated by Django 4.2.6 on 2023-12-05 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Team',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='tasks.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='tasks.task'),
        ),
    ]
