# Generated by Django 4.2.6 on 2023-12-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_team_team_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='tasks',
        ),
        migrations.AddField(
            model_name='user',
            name='invites',
            field=models.ManyToManyField(blank=True, related_name='invites', to='tasks.team'),
        ),
    ]
