# Generated by Django 4.2.8 on 2023-12-16 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_team_user_teams'),
        ('tasks', '0007_user_teams_alter_task_status_alter_team_members_and_more'),
    ]

    operations = [
    ]
