# Generated by Django 4.2.6 on 2023-12-13 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_user_teams_alter_task_status_alter_team_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='team_tasks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_tasks', to='tasks.team'),
        ),
    ]
